[package]
name = "my-project"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"
ocl = "0.20"
num_cpus = "1.16"

# Uncomment below only if you're using an actual 'rdp' crate
# rdp = "0.1.0"   # You need to replace with the actual crate version or remove if custom
